### ISSUE TITLE
macOS Sierra下，打开Slim Text只显示两条黑线

### ISSUE THREAD

**Issue by zjyExcelsior** [tylerlong/slim_text#25]
控制台报如下错误：

```
Error in response to storage.get: TypeError: this.file_manager.exists is not a function
    at e.FileManager.e.exists (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/file_manager.js:1:599)
    at null.callback (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/util.js:1:1036)
    at t.Util.t.last_folder (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/util.js:1:975)
    at HTMLDocument.<anonymous> (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/main.js:1:207)
    at j (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/jquery.js:2:26676)
    at Object.fireWith [as resolveWith] (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/jquery.js:2:27489)
    at Function.ready (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/jquery.js:2:29283)
    at HTMLDocument.I (chrome-extension://efgpjeojnoblodlofkhmhgghdfadmeoc/js/jquery.js:2:29453)
```

**Comment by tylerlong** [comment]
此项目已经废弃了。 原因是 Chrome 已经不再支持 NPAPI。

**Comment by zjyExcelsior** [comment]
嗯，发现代码也是几年前了的～～
